### ISSUE TITLE
Config isn't parsed into the correct classes, just POJOs

### ISSUE THREAD

**Issue by NickBolles** [derbenoo/ts-configurable#37]
I added a few assertions to the tests to illustrate this issue, see this branch:
https://github.com/NickBolles/ts-configurable

Could we use Reflection, or just recognize that the property isn't a POJO and instead of replacing it copy values to it? I'm wondering what the best route would be, but I can submit a PR once we decide.

**Comment by derbenoo** [comment]
@NickBolles Thank you for submitting the issue and suggestion this improvement to the ts-configurable library. I finally got around to implementing this, based on the tests you kindly provided in your pull request.

Commit implementing the suggestion: https://github.com/derbenoo/ts-configurable/commit/7c537c09d66614d1090c12522557cb135b7b273e

Tests merged and failing: https://circleci.com/gh/derbenoo/ts-configurable/149

Feature implemented and tests succeeding: https://circleci.com/gh/derbenoo/ts-configurable/150

:pray:

**Comment by NickBolles** [comment]
@derbenoo Awesome!! I actually updated my packages in my project and a test that I had, which was a workaround for this started failing. Then I came to find this! Thank you! now I can remove my workaround!

**Comment by NickBolles** [comment]
@derbenoo also, the code changes were way more concise than what I was going to try to do. Nice!
